//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code auto-generated. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"fmt"
	apiresourceapiv1alpha1 "github.com/kcp-dev/kcp/pkg/apis/apiresource/v1alpha1"
	apiresourcev1alpha1 "github.com/kcp-dev/kcp/pkg/client/clientset/versioned/typed/apiresource/v1alpha1"

	kcp "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/apimachinery/pkg/logicalcluster"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/rest"
)

type WrappedApiresourceV1alpha1 struct {
	Cluster  logicalcluster.LogicalCluster
	Delegate apiresourcev1alpha1.ApiresourceV1alpha1Interface
}

func (w *WrappedApiresourceV1alpha1) RESTClient() rest.Interface {
	return w.Delegate.RESTClient()
}

func (w *WrappedApiresourceV1alpha1) APIResourceImports() apiresourcev1alpha1.APIResourceImportInterface {
	return &wrappedAPIResourceImport{
		cluster:  w.Cluster,
		delegate: w.Delegate.APIResourceImports(),
	}
}

type wrappedAPIResourceImport struct {
	cluster  logicalcluster.LogicalCluster
	delegate apiresourcev1alpha1.APIResourceImportInterface
}

func (w *wrappedAPIResourceImport) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}

func (w *wrappedAPIResourceImport) Create(ctx context.Context, aPIResourceImport *apiresourceapiv1alpha1.APIResourceImport, opts metav1.CreateOptions) (*apiresourceapiv1alpha1.APIResourceImport, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Create(ctx, aPIResourceImport, opts)
}

func (w *wrappedAPIResourceImport) Update(ctx context.Context, aPIResourceImport *apiresourceapiv1alpha1.APIResourceImport, opts metav1.UpdateOptions) (*apiresourceapiv1alpha1.APIResourceImport, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Update(ctx, aPIResourceImport, opts)
}

func (w *wrappedAPIResourceImport) UpdateStatus(ctx context.Context, aPIResourceImport *apiresourceapiv1alpha1.APIResourceImport, opts metav1.UpdateOptions) (*apiresourceapiv1alpha1.APIResourceImport, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.UpdateStatus(ctx, aPIResourceImport, opts)
}

func (w *wrappedAPIResourceImport) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.Delete(ctx, name, opts)
}

func (w *wrappedAPIResourceImport) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listopts metav1.ListOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.DeleteCollection(ctx, opts, listopts)
}

func (w *wrappedAPIResourceImport) Get(ctx context.Context, name string, opts metav1.GetOptions) (*apiresourceapiv1alpha1.APIResourceImport, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Get(ctx, name, opts)
}

func (w *wrappedAPIResourceImport) List(ctx context.Context, opts metav1.ListOptions) (*apiresourceapiv1alpha1.APIResourceImportList, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.List(ctx, opts)
}

func (w *wrappedAPIResourceImport) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Watch(ctx, opts)
}

func (w *wrappedAPIResourceImport) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *apiresourceapiv1alpha1.APIResourceImport, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Patch(ctx, name, pt, data, opts, subresources...)
}

func (w *WrappedApiresourceV1alpha1) NegotiatedAPIResources() apiresourcev1alpha1.NegotiatedAPIResourceInterface {
	return &wrappedNegotiatedAPIResource{
		cluster:  w.Cluster,
		delegate: w.Delegate.NegotiatedAPIResources(),
	}
}

type wrappedNegotiatedAPIResource struct {
	cluster  logicalcluster.LogicalCluster
	delegate apiresourcev1alpha1.NegotiatedAPIResourceInterface
}

func (w *wrappedNegotiatedAPIResource) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}

func (w *wrappedNegotiatedAPIResource) Create(ctx context.Context, negotiatedAPIResource *apiresourceapiv1alpha1.NegotiatedAPIResource, opts metav1.CreateOptions) (*apiresourceapiv1alpha1.NegotiatedAPIResource, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Create(ctx, negotiatedAPIResource, opts)
}

func (w *wrappedNegotiatedAPIResource) Update(ctx context.Context, negotiatedAPIResource *apiresourceapiv1alpha1.NegotiatedAPIResource, opts metav1.UpdateOptions) (*apiresourceapiv1alpha1.NegotiatedAPIResource, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Update(ctx, negotiatedAPIResource, opts)
}

func (w *wrappedNegotiatedAPIResource) UpdateStatus(ctx context.Context, negotiatedAPIResource *apiresourceapiv1alpha1.NegotiatedAPIResource, opts metav1.UpdateOptions) (*apiresourceapiv1alpha1.NegotiatedAPIResource, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.UpdateStatus(ctx, negotiatedAPIResource, opts)
}

func (w *wrappedNegotiatedAPIResource) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.Delete(ctx, name, opts)
}

func (w *wrappedNegotiatedAPIResource) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listopts metav1.ListOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.DeleteCollection(ctx, opts, listopts)
}

func (w *wrappedNegotiatedAPIResource) Get(ctx context.Context, name string, opts metav1.GetOptions) (*apiresourceapiv1alpha1.NegotiatedAPIResource, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Get(ctx, name, opts)
}

func (w *wrappedNegotiatedAPIResource) List(ctx context.Context, opts metav1.ListOptions) (*apiresourceapiv1alpha1.NegotiatedAPIResourceList, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.List(ctx, opts)
}

func (w *wrappedNegotiatedAPIResource) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Watch(ctx, opts)
}

func (w *wrappedNegotiatedAPIResource) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *apiresourceapiv1alpha1.NegotiatedAPIResource, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Patch(ctx, name, pt, data, opts, subresources...)
}
