//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code auto-generated. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"fmt"
	workloadapiv1alpha1 "github.com/kcp-dev/kcp/pkg/apis/workload/v1alpha1"
	workloadv1alpha1 "github.com/kcp-dev/kcp/pkg/client/clientset/versioned/typed/workload/v1alpha1"

	kcp "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/apimachinery/pkg/logicalcluster"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/rest"
)

type WrappedWorkloadV1alpha1 struct {
	Cluster  logicalcluster.LogicalCluster
	Delegate workloadv1alpha1.WorkloadV1alpha1Interface
}

func (w *WrappedWorkloadV1alpha1) RESTClient() rest.Interface {
	return w.Delegate.RESTClient()
}

func (w *WrappedWorkloadV1alpha1) WorkloadClusters() workloadv1alpha1.WorkloadClusterInterface {
	return &wrappedWorkloadCluster{
		cluster:  w.Cluster,
		delegate: w.Delegate.WorkloadClusters(),
	}
}

type wrappedWorkloadCluster struct {
	cluster  logicalcluster.LogicalCluster
	delegate workloadv1alpha1.WorkloadClusterInterface
}

func (w *wrappedWorkloadCluster) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}

func (w *wrappedWorkloadCluster) Create(ctx context.Context, workloadCluster *workloadapiv1alpha1.WorkloadCluster, opts metav1.CreateOptions) (*workloadapiv1alpha1.WorkloadCluster, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Create(ctx, workloadCluster, opts)
}

func (w *wrappedWorkloadCluster) Update(ctx context.Context, workloadCluster *workloadapiv1alpha1.WorkloadCluster, opts metav1.UpdateOptions) (*workloadapiv1alpha1.WorkloadCluster, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Update(ctx, workloadCluster, opts)
}

func (w *wrappedWorkloadCluster) UpdateStatus(ctx context.Context, workloadCluster *workloadapiv1alpha1.WorkloadCluster, opts metav1.UpdateOptions) (*workloadapiv1alpha1.WorkloadCluster, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.UpdateStatus(ctx, workloadCluster, opts)
}

func (w *wrappedWorkloadCluster) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.Delete(ctx, name, opts)
}

func (w *wrappedWorkloadCluster) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listopts metav1.ListOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.DeleteCollection(ctx, opts, listopts)
}

func (w *wrappedWorkloadCluster) Get(ctx context.Context, name string, opts metav1.GetOptions) (*workloadapiv1alpha1.WorkloadCluster, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Get(ctx, name, opts)
}

func (w *wrappedWorkloadCluster) List(ctx context.Context, opts metav1.ListOptions) (*workloadapiv1alpha1.WorkloadClusterList, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.List(ctx, opts)
}

func (w *wrappedWorkloadCluster) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Watch(ctx, opts)
}

func (w *wrappedWorkloadCluster) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *workloadapiv1alpha1.WorkloadCluster, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Patch(ctx, name, pt, data, opts, subresources...)
}
